version: '3.8'

services:
  # Django Web Application
  web:
    build: .
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=todoproject.settings
    volumes:
      - .:/app
      - /app/venv
    command: python manage.py runserver 0.0.0.0:8000

  # Optional: PostgreSQL Database (if you want to use it later)
  # db:
  #   image: postgres:15-alpine
  #   container_name: todo-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_DB=tododb
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
#     driver: local
